import type { Animal, Photo } from "@/types";

/**
 * Fiches animaux du jeu de départ.
 * Chargées en base par `npm run db:seed` — ce fichier n'est plus lu ensuite.
 */

/**
 * Photo d'une fiche animal.
 *
 * Une seule par animal : les photos livrées sont des images d'illustration,
 * pas les animaux réels. En mettre plusieurs donnerait l'impression trompeuse
 * qu'il s'agit du même animal photographié sous plusieurs angles.
 */
function galerie(slug: string, alt: string): Photo[] {
  return [{ src: `/images/animaux/${slug}.jpg`, alt }];
}

/**
 * Fiches animaux.
 *
 * Chaque fiche porte les mentions prévues par le code rural pour les offres
 * de cession d'animaux (art. L.214-8-1) : espèce, sexe, âge, numéro
 * d'identification et race — `race: null` signifiant explicitement
 * « n'appartient pas à une race ».
 *
 * Une fiche adoptée n'est jamais supprimée : elle passe au statut « adopte »,
 * son formulaire disparaît et laisse place au récit de l'adoption.
 */
export const animaux: Animal[] = [
  /* ---------------------------------------------------------------- */
  {
    id: "ani-001",
    slug: "oslo",
    nom: "Oslo",
    espece: "chien",
    sexe: "male",
    race: null,
    age: "3 ans",
    ageMois: 36,
    dateNaissanceEstimee: "2023-04-12",
    identification: "250268500123456",
    taille: "moyen",
    poidsKg: 21,
    commune: "Lunel (34)",
    photoPrincipale: {
      src: "/images/animaux/oslo.jpg",
      alt: "Oslo, chien proposé à l’adoption par ASAD",
    },
    galerie: galerie("oslo", "Oslo, chien proposé à l’adoption par ASAD"),
    descriptionCourte:
      "Oslo est un chien équilibré et affectueux, à l’aise en balade comme à la maison. Il marche bien en laisse et adore les longues sorties.",
    histoire: [
      "Oslo a été trouvé errant sur une route départementale de l’Hérault, sans collier ni puce lisible. Personne ne l’a réclamé pendant les huit jours de garde légale à la fourrière.",
      "Recueilli par l’association, il a rejoint une famille d’accueil à Lunel. En trois semaines, il avait repris du poids, retrouvé le goût du jeu et appris à marcher sans tirer. Aujourd’hui il attend simplement la bonne famille.",
    ],
    caractere: ["Doux", "Joueur", "Obéissant", "Sociable", "Calme en intérieur", "Curieux", "Attaché"],
    caractereNote:
      "Oslo demande de la présence sans être envahissant : il s’installe près de vous et attend son moment. Il connaît « assis », « couché » et le rappel en extérieur.",
    compatChiens: "oui",
    compatChats: "a_tester",
    compatEnfants: "avec_conditions",
    compatNotes: {
      chiens: "S’entend avec les mâles comme les femelles, après présentation en terrain neutre.",
      chats: "Jamais mis en présence d’un chat : une rencontre encadrée est indispensable.",
      enfants: "Très doux, mais son gabarit demande la présence d’un adulte avec les plus jeunes. Dès 8 ans.",
    },
    sante: {
      identifie: true,
      vaccine: true,
      sterilise: true,
      resume: "En parfaite santé, aucun traitement en cours.",
    },
    environnement:
      "Oslo a besoin d’un foyer actif, capable de lui offrir de vraies sorties quotidiennes. Il vit très bien en maison comme en appartement à condition de sortir trois fois par jour.",
    environnementPoints: [
      "Jardin clôturé apprécié, mais non obligatoire",
      "Trois sorties quotidiennes dont une longue",
      "Présence régulière à la maison les premières semaines",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Vous remplissez le formulaire en ligne, rattaché à la fiche d’Oslo." },
      { titre: "L’échange", texte: "Un bénévole vous rappelle sous cinq jours ouvrés pour parler de votre foyer." },
      { titre: "La rencontre", texte: "Vous rencontrez Oslo chez sa famille d’accueil, autant de fois que nécessaire." },
      { titre: "L’adoption", texte: "Visite du domicile, signature du contrat, puis suivi pendant six mois." },
    ],
    fraisAdoption: 250,
    statut: "a_adopter",
    afficherSurAccueil: true,
    dateArrivee: "2026-05-18",
    datePublication: "2026-06-02",
    nbDemandes: 3,
    familleAccueil: "Famille Bertrand, Lunel",
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-002",
    slug: "plume",
    nom: "Plume",
    espece: "chat",
    sexe: "femelle",
    race: null,
    age: "1 an",
    ageMois: 12,
    dateNaissanceEstimee: "2025-06-02",
    identification: "250268500234567",
    taille: "petit",
    poidsKg: 3.4,
    commune: "Montpellier (34)",
    photoPrincipale: {
      src: "/images/animaux/plume.jpg",
      alt: "Plume, chatte proposée à l’adoption par ASAD",
    },
    galerie: galerie("plume", "Plume, chatte proposée à l’adoption par ASAD"),
    descriptionCourte:
      "Plume est une jeune chatte curieuse et bavarde. Elle réclame des caresses dès qu’on s’assied et suit sa famille d’accueil de pièce en pièce.",
    histoire: [
      "Plume est née dans un jardin de Montpellier, d’une chatte errante non stérilisée. Elle a été recueillie à huit semaines avec ses frères et sœurs.",
      "Sociabilisée en famille d’accueil, elle est aujourd’hui parfaitement à l’aise avec les humains et les autres chats.",
    ],
    caractere: ["Curieuse", "Câline", "Bavarde", "Joueuse", "Sociable"],
    caractereNote:
      "Plume vit au rythme de sa famille : elle joue le matin, dort l’après-midi et réclame ses câlins le soir.",
    compatChiens: "a_tester",
    compatChats: "oui",
    compatEnfants: "oui",
    compatNotes: {
      chats: "A grandi avec sa fratrie, l’adoption avec un autre chat est idéale.",
      enfants: "Patiente et jamais griffeuse.",
    },
    sante: { identifie: true, vaccine: true, sterilise: true, resume: "Bilan complet réalisé, aucune anomalie." },
    environnement:
      "Plume peut vivre en appartement, à condition que les fenêtres et le balcon soient sécurisés. Elle a besoin de compagnie dans la journée.",
    environnementPoints: [
      "Fenêtres et balcon sécurisés obligatoires",
      "Pas de sortie libre en extérieur la première année",
      "Présence d’un autre chat vivement conseillée",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à la fiche de Plume." },
      { titre: "L’échange", texte: "Un bénévole vous rappelle pour parler de votre logement." },
      { titre: "La rencontre", texte: "Rencontre chez sa famille d’accueil à Montpellier." },
      { titre: "L’adoption", texte: "Contrat signé, puis nouvelles régulières pendant six mois." },
    ],
    fraisAdoption: 150,
    statut: "a_adopter",
    afficherSurAccueil: true,
    dateArrivee: "2026-06-24",
    datePublication: "2026-07-05",
    nbDemandes: 5,
    familleAccueil: "Famille Nguyen, Montpellier",
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-003",
    slug: "nala",
    nom: "Nala",
    espece: "chien",
    sexe: "femelle",
    race: "Labrador croisé",
    age: "5 ans",
    ageMois: 60,
    dateNaissanceEstimee: "2021-02-20",
    identification: "250268500345678",
    taille: "moyen",
    poidsKg: 24,
    commune: "Nîmes (30)",
    photoPrincipale: {
      src: "/images/animaux/nala.jpg",
      alt: "Nala, chienne proposée à l’adoption par ASAD",
    },
    galerie: galerie("nala", "Nala, chienne proposée à l’adoption par ASAD"),
    descriptionCourte:
      "Nala est une chienne calme, idéale pour une première adoption. Elle apprécie la compagnie humaine et se montre très douce avec les enfants.",
    histoire: [
      "Nala a été abandonnée après un déménagement de ses propriétaires, attachée devant la porte d’un refuge de Nîmes.",
      "Il lui a fallu quelques semaines pour retrouver le sourire. Elle a depuis repris goût aux promenades et aux jeux de recherche.",
    ],
    caractere: ["Calme", "Fidèle", "Douce", "Patiente", "Affectueuse"],
    caractereNote: "Nala est une chienne posée qui n’aboie presque jamais et supporte bien la solitude en journée.",
    compatChiens: "oui",
    compatChats: "non",
    compatEnfants: "oui",
    compatNotes: {
      chats: "Poursuit les chats en extérieur : foyer sans chat impératif.",
      enfants: "Très douce, testée avec des enfants de 4 et 9 ans.",
    },
    sante: {
      identifie: true,
      vaccine: true,
      sterilise: true,
      resume: "Bonne santé générale.",
      traitement: "Léger surpoids : alimentation contrôlée recommandée les premiers mois.",
    },
    environnement:
      "Nala convient à un foyer calme, avec ou sans jardin, du moment qu’elle sort régulièrement. Elle est parfaite pour une première adoption.",
    environnementPoints: [
      "Foyer sans chat",
      "Deux à trois sorties quotidiennes",
      "Alimentation contrôlée les six premiers mois",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à la fiche de Nala." },
      { titre: "L’échange", texte: "Appel d’un bénévole sous cinq jours ouvrés." },
      { titre: "La rencontre", texte: "Rencontre au refuge partenaire de Nîmes." },
      { titre: "L’adoption", texte: "Visite du domicile, contrat, puis suivi de six mois." },
    ],
    fraisAdoption: 250,
    statut: "a_adopter",
    afficherSurAccueil: true,
    dateArrivee: "2026-04-02",
    datePublication: "2026-04-15",
    nbDemandes: 2,
    familleAccueil: "Refuge partenaire, Nîmes",
  },

  /* ------------------------- Urgences ------------------------------ */
  {
    id: "ani-004",
    slug: "rio",
    nom: "Rio",
    espece: "chien",
    sexe: "male",
    race: null,
    age: "4 ans",
    ageMois: 48,
    dateNaissanceEstimee: "2022-03-15",
    identification: "250268500456789",
    taille: "moyen",
    poidsKg: 19,
    commune: "Lunel (34)",
    photoPrincipale: {
      src: "/images/animaux/rio.jpg",
      alt: "Rio, chien proposé à l’adoption par ASAD",
    },
    galerie: galerie("rio", "Rio, chien proposé à l’adoption par ASAD"),
    descriptionCourte:
      "Rio est un chien courageux et confiant malgré la douleur. Il accepte tous les soins sans jamais se plaindre.",
    histoire: [
      "Rio a été recueilli après avoir été percuté par un véhicule sur une route de l’Hérault.",
      "L’examen a révélé une rupture des ligaments croisés du genou arrière droit, qui nécessite une opération rapide pour lui éviter des douleurs chroniques.",
    ],
    caractere: ["Courageux", "Confiant", "Patient", "Doux"],
    compatChiens: "oui",
    compatChats: "a_tester",
    compatEnfants: "oui",
    sante: {
      identifie: true,
      vaccine: true,
      sterilise: false,
      resume: "Rupture des ligaments croisés du genou arrière droit.",
      traitement: "Opération à programmer sous quinze jours, puis huit semaines de convalescence stricte.",
    },
    environnement:
      "Rio ne pourra rejoindre une famille qu’après son opération et sa convalescence. Il aura alors besoin d’un foyer capable de respecter un repos strict.",
    environnementPoints: [
      "Adoption possible après la convalescence",
      "Repos strict pendant huit semaines",
      "Pas d’escaliers les premières semaines",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Vous pouvez déposer une demande dès maintenant." },
      { titre: "L’opération", texte: "Rio est opéré dès que la collecte atteint son objectif." },
      { titre: "La convalescence", texte: "Huit semaines chez sa famille d’accueil." },
      { titre: "L’adoption", texte: "Rencontre, contrat et suivi une fois rétabli." },
    ],
    fraisAdoption: 250,
    statut: "urgent",
    afficherSurAccueil: true,
    dateArrivee: "2026-08-08",
    datePublication: "2026-08-09",
    nbDemandes: 1,
    familleAccueil: "Clinique vétérinaire, Lunel",
    urgence: {
      motif: "Rupture des ligaments croisés. Il doit être opéré dans les quinze jours.",
      delai: "Opération sous 15 jours",
      ctaLabel: "Aider Rio",
    },
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-005",
    slug: "milo",
    nom: "Milo",
    espece: "chat",
    sexe: "male",
    race: null,
    age: "8 ans",
    ageMois: 96,
    dateNaissanceEstimee: "2018-05-10",
    identification: "250268500567890",
    taille: "moyen",
    poidsKg: 4.6,
    commune: "Alès (30)",
    photoPrincipale: {
      src: "/images/animaux/milo.jpg",
      alt: "Milo, chat proposé à l’adoption par ASAD",
    },
    galerie: galerie("milo", "Milo, chat proposé à l’adoption par ASAD"),
    descriptionCourte:
      "Milo est un chat posé, habitué à la vie d’intérieur. Il cherche un coin tranquille et une famille patiente.",
    histoire: [
      "Déposé en fourrière sans identification, Milo a dépassé son délai légal de garde.",
      "Sans famille d’accueil disponible sous 48 heures, son avenir est incertain. L’association cherche à financer sa sortie.",
    ],
    caractere: ["Posé", "Discret", "Affectueux", "Indépendant"],
    compatChiens: "a_tester",
    compatChats: "a_tester",
    compatEnfants: "avec_conditions",
    compatNotes: { enfants: "Préfère les foyers calmes, sans jeunes enfants." },
    sante: {
      identifie: true,
      vaccine: true,
      sterilise: true,
      resume: "État général correct pour son âge.",
      traitement: "Bilan sanguin à refaire dès l’arrivée en famille d’accueil.",
    },
    environnement:
      "Milo a besoin d’un intérieur calme et prévisible. Il n’aime ni le bruit ni les changements brutaux.",
    environnementPoints: ["Vie en intérieur", "Foyer calme", "Sans jeunes enfants de préférence"],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne, traité en priorité." },
      { titre: "La sortie", texte: "Sa sortie de fourrière est financée par la collecte." },
      { titre: "L’accueil", texte: "Placement immédiat en famille d’accueil." },
      { titre: "L’adoption", texte: "Adoption possible dans la foulée." },
    ],
    fraisAdoption: 100,
    statut: "urgent",
    afficherSurAccueil: true,
    dateArrivee: "2026-08-14",
    datePublication: "2026-08-14",
    nbDemandes: 0,
    familleAccueil: "Fourrière, Alès",
    urgence: {
      motif: "Délai de garde en fourrière dépassé. Il cherche une famille d’accueil.",
      delai: "Sortie sous 48 heures",
      ctaLabel: "Accueillir Milo",
    },
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-006",
    slug: "java",
    nom: "Java",
    espece: "chien",
    sexe: "femelle",
    race: null,
    age: "2 ans",
    ageMois: 24,
    dateNaissanceEstimee: "2024-01-30",
    identification: "250268500678901",
    taille: "moyen",
    poidsKg: 14,
    commune: "Sète (34)",
    photoPrincipale: {
      src: "/images/animaux/java.jpg",
      alt: "Java, chienne proposée à l’adoption par ASAD",
    },
    galerie: galerie("java", "Java, chienne proposée à l’adoption par ASAD"),
    descriptionCourte:
      "Java reprend des forces jour après jour. Encore fragile, elle se montre déjà très reconnaissante envers ceux qui s’occupent d’elle.",
    histoire: [
      "Java a été signalée par un voisin dans un terrain abandonné près de Sète, très amaigrie et déshydratée.",
      "Elle suit un protocole de renutrition sous contrôle vétérinaire, avec un contrôle hebdomadaire.",
    ],
    caractere: ["Reconnaissante", "Sensible", "Volontaire", "Douce"],
    compatChiens: "oui",
    compatChats: "a_tester",
    compatEnfants: "a_tester",
    sante: {
      identifie: true,
      vaccine: true,
      sterilise: false,
      resume: "Dénutrition sévère à l’arrivée, état en nette amélioration.",
      traitement: "Renutrition progressive et traitement vétérinaire quotidien. Contrôle hebdomadaire.",
    },
    environnement:
      "Java aura besoin d’un foyer patient, capable de poursuivre son suivi vétérinaire et de respecter son rythme.",
    environnementPoints: [
      "Adoption envisageable à la fin du protocole de soins",
      "Disponibilité pour les rendez-vous vétérinaires",
      "Foyer calme et rassurant",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à sa fiche." },
      { titre: "Les soins", texte: "Java termine son protocole de renutrition." },
      { titre: "La rencontre", texte: "Rencontre chez sa famille d’accueil à Sète." },
      { titre: "L’adoption", texte: "Contrat et suivi rapproché la première année." },
    ],
    fraisAdoption: 250,
    statut: "urgent",
    afficherSurAccueil: true,
    dateArrivee: "2026-07-29",
    datePublication: "2026-07-30",
    nbDemandes: 2,
    familleAccueil: "Famille Roux, Sète",
    urgence: {
      motif: "Recueillie très amaigrie. Elle est sous traitement vétérinaire quotidien.",
      delai: "Soins en cours",
      ctaLabel: "Aider Java",
    },
  },

  /* ------------------------ Catalogue ------------------------------ */
  {
    id: "ani-007",
    slug: "bao",
    nom: "Bao",
    espece: "chat",
    sexe: "male",
    race: null,
    age: "2 ans",
    ageMois: 24,
    dateNaissanceEstimee: "2024-03-08",
    identification: "250268500789012",
    taille: "petit",
    poidsKg: 4.1,
    commune: "Béziers (34)",
    photoPrincipale: { src: "/images/animaux/bao.jpg", alt: "Bao, chat proposé à l’adoption par ASAD" },
    galerie: galerie("bao", "Bao, chat proposé à l’adoption par ASAD"),
    descriptionCourte:
      "Bao est un chat vif, grand amateur de jeux de chasse. Il s’entend très bien avec ses congénères.",
    histoire: [
      "Bao a été recueilli lors d’une campagne de stérilisation d’un groupe de chats libres à Béziers.",
      "Encore jeune, il a été sociabilisé en quelques semaines et réclame désormais l’attention.",
    ],
    caractere: ["Vif", "Joueur", "Sociable", "Malin"],
    compatChiens: "a_tester",
    compatChats: "oui",
    compatEnfants: "oui",
    sante: { identifie: true, vaccine: true, sterilise: true, resume: "En pleine forme." },
    environnement:
      "Bao a besoin de compagnie et de stimulation. Une adoption avec un autre chat lui convient particulièrement.",
    environnementPoints: [
      "Adoption avec un congénère conseillée",
      "Fenêtres sécurisées",
      "Arbre à chat et jeux indispensables",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à sa fiche." },
      { titre: "L’échange", texte: "Appel d’un bénévole sous cinq jours ouvrés." },
      { titre: "La rencontre", texte: "Rencontre chez sa famille d’accueil." },
      { titre: "L’adoption", texte: "Contrat signé et suivi de six mois." },
    ],
    fraisAdoption: 150,
    statut: "a_adopter",
    afficherSurAccueil: false,
    dateArrivee: "2026-07-11",
    datePublication: "2026-07-18",
    nbDemandes: 1,
    familleAccueil: "Famille Lopez, Béziers",
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-008",
    slug: "gribouille",
    nom: "Gribouille",
    espece: "chat",
    sexe: "femelle",
    race: null,
    age: "6 ans",
    ageMois: 72,
    dateNaissanceEstimee: "2020-03-22",
    identification: "250268500901234",
    taille: "moyen",
    poidsKg: 3.9,
    commune: "Uzès (30)",
    photoPrincipale: { src: "/images/animaux/gribouille.jpg", alt: "Gribouille, chatte proposée à l’adoption par ASAD" },
    galerie: galerie("gribouille", "Gribouille, chatte proposée à l’adoption par ASAD"),
    descriptionCourte:
      "Gribouille est une chatte indépendante qui choisit ses moments de câlins. Elle a besoin d’un foyer calme et prévisible.",
    histoire: [
      "Retrouvée dans un logement laissé vacant à Uzès, Gribouille avait survécu seule plusieurs semaines.",
      "Elle a repris confiance progressivement et accepte aujourd’hui les caresses, à son rythme.",
    ],
    caractere: ["Indépendante", "Observatrice", "Douce", "Discrète"],
    compatChiens: "non",
    compatChats: "a_tester",
    compatEnfants: "avec_conditions",
    compatNotes: { enfants: "Dès 10 ans, dans un foyer calme." },
    sante: { identifie: true, vaccine: true, sterilise: true, resume: "Bonne santé, suivi dentaire à prévoir." },
    environnement:
      "Gribouille se sentira bien dans un foyer calme, où elle pourra observer avant de s’approcher.",
    environnementPoints: ["Foyer calme", "Adoption en chat unique conseillée", "Sans chien"],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à sa fiche." },
      { titre: "L’échange", texte: "Appel d’un bénévole." },
      { titre: "La rencontre", texte: "Rencontre chez sa famille d’accueil à Uzès." },
      { titre: "L’adoption", texte: "Contrat signé et suivi de six mois." },
    ],
    fraisAdoption: 120,
    statut: "a_adopter",
    afficherSurAccueil: false,
    dateArrivee: "2026-06-05",
    datePublication: "2026-06-14",
    nbDemandes: 0,
    familleAccueil: "Famille Girard, Uzès",
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-009",
    slug: "titan",
    nom: "Titan",
    espece: "chien",
    sexe: "male",
    race: "Beauceron croisé",
    age: "6 ans",
    ageMois: 72,
    dateNaissanceEstimee: "2020-08-25",
    identification: "250268501234567",
    taille: "grand",
    poidsKg: 34,
    commune: "Vauvert (30)",
    photoPrincipale: { src: "/images/animaux/titan.jpg", alt: "Titan, chien proposé à l’adoption par ASAD" },
    galerie: galerie("titan", "Titan, chien proposé à l’adoption par ASAD"),
    descriptionCourte:
      "Titan est un grand chien très attaché à ses humains. Il a besoin d’un cadre clair et d’une présence régulière.",
    histoire: [
      "Saisi lors d’une procédure de maltraitance dans le Gard, Titan est arrivé méfiant et sur la défensive.",
      "Il a mis plusieurs mois à refaire confiance. Il est aujourd’hui prêt pour une adoption, auprès de personnes expérimentées.",
    ],
    caractere: ["Loyal", "Protecteur", "Sensible", "Intelligent"],
    caractereNote: "Titan a besoin de repères stables. Une reprise d’éducation avec un professionnel est demandée.",
    compatChiens: "a_tester",
    compatChats: "non",
    compatEnfants: "avec_conditions",
    compatNotes: { enfants: "Dès 12 ans, avec des adultes présents." },
    sante: { identifie: true, vaccine: true, sterilise: true, resume: "Bonne santé, aucune séquelle physique." },
    environnement:
      "Titan a besoin d’un jardin clôturé et de maîtres expérimentés, capables de poursuivre son travail d’éducation.",
    environnementPoints: [
      "Expérience des grands chiens indispensable",
      "Jardin clôturé de 1,80 m minimum",
      "Plusieurs rencontres avant l’adoption",
    ],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à sa fiche." },
      { titre: "L’échange", texte: "Entretien approfondi avec un bénévole référent." },
      { titre: "Les rencontres", texte: "Au moins trois rencontres avant toute décision." },
      { titre: "L’adoption", texte: "Visite du domicile, contrat, suivi renforcé d’un an." },
    ],
    fraisAdoption: 250,
    statut: "a_adopter",
    afficherSurAccueil: false,
    dateArrivee: "2026-03-14",
    datePublication: "2026-05-20",
    nbDemandes: 1,
    familleAccueil: "Refuge partenaire, Vauvert",
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-010",
    slug: "caline",
    nom: "Câline",
    espece: "chat",
    sexe: "femelle",
    race: null,
    age: "4 ans",
    ageMois: 48,
    dateNaissanceEstimee: "2022-05-19",
    identification: "250268501012345",
    taille: "petit",
    poidsKg: 3.6,
    commune: "Lattes (34)",
    photoPrincipale: { src: "/images/animaux/caline.jpg", alt: "Câline, chatte proposée à l’adoption par ASAD" },
    galerie: galerie("caline", "Câline, chatte proposée à l’adoption par ASAD"),
    descriptionCourte:
      "Câline porte bien son nom : elle réclame l’attention en permanence et ronronne dès qu’on la touche.",
    histoire: [
      "Câline a été confiée à l’association après le décès de sa propriétaire.",
      "Elle a mis quelques semaines à s’adapter, puis a retrouvé toute sa gaieté auprès de sa famille d’accueil.",
    ],
    caractere: ["Câline", "Sociable", "Ronronneuse", "Calme"],
    compatChiens: "a_tester",
    compatChats: "oui",
    compatEnfants: "oui",
    sante: { identifie: true, vaccine: true, sterilise: true, resume: "En bonne santé." },
    environnement: "Câline s’adapte à tout foyer où elle recevra de l’attention quotidienne.",
    environnementPoints: ["Vie en intérieur", "Présence quotidienne", "Fenêtres sécurisées"],
    conditions: [
      { titre: "Votre demande", texte: "Formulaire en ligne rattaché à sa fiche." },
      { titre: "L’échange", texte: "Appel d’un bénévole." },
      { titre: "La rencontre", texte: "Rencontre chez sa famille d’accueil." },
      { titre: "L’adoption", texte: "Contrat signé et suivi de six mois." },
    ],
    fraisAdoption: 150,
    statut: "reserve",
    afficherSurAccueil: false,
    dateArrivee: "2026-06-19",
    datePublication: "2026-06-28",
    nbDemandes: 4,
    familleAccueil: "Famille Meyer, Lattes",
    reserveDepuis: "2026-08-19",
  },

  /* ------------------------- Adoptés ------------------------------- */
  {
    id: "ani-011",
    slug: "ficelle",
    nom: "Ficelle",
    espece: "chat",
    sexe: "femelle",
    race: null,
    age: "3 ans",
    ageMois: 36,
    dateNaissanceEstimee: "2023-01-09",
    identification: "250268501345678",
    taille: "petit",
    poidsKg: 3.7,
    commune: "Frontignan (34)",
    photoPrincipale: { src: "/images/animaux/ficelle.jpg", alt: "Ficelle, chatte adoptée grâce à ASAD" },
    galerie: galerie("ficelle", "Ficelle, chatte adoptée grâce à ASAD"),
    descriptionCourte: "Ficelle est une chatte tendre qui a trouvé sa famille au printemps 2026.",
    histoire: [
      "Recueillie après un abandon en pleine rue à Frontignan, Ficelle a passé quatre mois en famille d’accueil.",
      "Elle a rencontré ses adoptants en avril et n’a plus jamais quitté leur canapé.",
    ],
    caractere: ["Tendre", "Discrète", "Câline"],
    compatChiens: "a_tester",
    compatChats: "oui",
    compatEnfants: "oui",
    sante: { identifie: true, vaccine: true, sterilise: true },
    environnement: "Ficelle vit aujourd’hui en appartement, entourée de sa famille.",
    environnementPoints: [],
    conditions: [],
    fraisAdoption: 150,
    statut: "adopte",
    afficherSurAccueil: false,
    dateArrivee: "2025-11-12",
    datePublication: "2025-12-01",
    nbDemandes: 6,
    suiteAdoption: {
      date: "2026-07-02",
      famille: "Famille Ferrand",
      recit:
        "Ficelle a pris ses marques en une semaine. Elle dort sur le canapé, réclame ses croquettes à heure fixe et vient nous chercher pour jouer.",
      citation: "Elle a transformé notre appartement en royaume, et on ne s’en plaint pas.",
      photo: { src: "/images/animaux/ficelle.jpg", alt: "Ficelle dans son nouveau foyer" },
    },
  },

  /* ---------------------------------------------------------------- */
  {
    id: "ani-012",
    slug: "lilou",
    nom: "Lilou",
    espece: "chat",
    sexe: "femelle",
    race: null,
    age: "3 ans",
    ageMois: 36,
    dateNaissanceEstimee: "2023-02-14",
    identification: "250268501456789",
    taille: "petit",
    poidsKg: 3.5,
    commune: "Bagnols-sur-Cèze (30)",
    photoPrincipale: { src: "/images/animaux/lilou.jpg", alt: "Lilou, chatte adoptée grâce à ASAD" },
    galerie: galerie("lilou", "Lilou, chatte adoptée grâce à ASAD"),
    descriptionCourte: "Lilou a rejoint la famille Martin en février 2026 et ne les a plus quittés.",
    histoire: [
      "Lilou a été recueillie très craintive, après plusieurs mois d’errance dans le Gard.",
      "Sa famille d’accueil a passé six semaines à l’apprivoiser avant qu’elle n’accepte le contact.",
    ],
    caractere: ["Câline", "Joueuse", "Pleine de vie"],
    compatChiens: "a_tester",
    compatChats: "oui",
    compatEnfants: "oui",
    sante: { identifie: true, vaccine: true, sterilise: true },
    environnement: "Lilou vit en maison avec un jardin sécurisé.",
    environnementPoints: [],
    conditions: [],
    fraisAdoption: 150,
    statut: "adopte",
    afficherSurAccueil: false,
    dateArrivee: "2025-09-20",
    datePublication: "2025-10-05",
    nbDemandes: 3,
    suiteAdoption: {
      date: "2026-08-20",
      famille: "Famille Martin",
      recit:
        "Adoptée il y a 6 mois, Lilou s’est parfaitement intégrée à notre famille. Câline, joueuse et pleine de vie, elle nous comble de bonheur chaque jour.",
      citation: "Adoptée il y a 6 mois, Lilou s’est parfaitement intégrée à notre famille.",
      photo: { src: "/images/animaux/lilou.jpg", alt: "Lilou dans son nouveau foyer" },
    },
  },
];
